entry_point: 0
stop_point: 3
parallel: true
max_pairwise_matches: 5500
num_passes: 3
use_csm: true
ip_per_tile: 2000
tri_weight: 0.05
tri_robust_threshold: 0.05
min_triangulation_angle: 0.1
heights_from_dem_uncertainty: 1.
ip_detect_method: 0
parameter_tolerance: 1e-8
min_matches: 200
match_first_to_last: null
num_iterations: 550
camera_position_weight: 0.0
rotation_weight: 0.0
robust_threshold: 1
overlap_limit: 20